import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { flowCorpus, checkedQuote } from '../src/lib/flow/candidates';
import { lexicalBreaks } from '../src/lib/flow/lexemes';

export async function buildCurated() {
  const require = createRequire(import.meta.url);
  const content = require('../miniprogram/content/passages.js');
  const sources = new Map((await flowCorpus()).map(row => [row.id, row]));
  const passages: Record<string, unknown> = {};
  for (const [id, entry] of Object.entries(content.passages) as Array<[string, any]>) {
    const source = sources.get(entry.sourceId);
    if (!source || source.text !== entry.fullText) throw new Error(`Curated source changed: ${id}`);
    const quote = source.text.includes(entry.quote) ? entry.quote : entry.quote.replace(/[，。！？；]$/, '');
    const range = checkedQuote(source, quote);
    passages[id] = { ...entry, quote, ...range, corpusVersion: source.corpusVersion,
      textHash: source.textHash, lexicalBreaks: lexicalBreaks(source.text) };
  }
  const payload = { passages, journeys: content.journeys, examples: content.examples || [],
    links: require('../miniprogram/content/branches.js'), entryWords: require('../miniprogram/content/entry-words.js') };
  const version = 'curated-' + createHash('sha256').update(JSON.stringify(payload)).digest('hex').slice(0, 16);
  const target = path.resolve('shared/flow/curated-data.js');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, '// Generated by scripts/build-flow-curated.ts; canonical corpus identities are verified at build time.\nmodule.exports = ' + JSON.stringify({ version, ...payload }) + ';\n');
  return { version, passages: Object.keys(passages).length };
}
