// Materialize a release-bound, publicly cacheable copy of the reviewed font set.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';

const root = process.cwd();
const hash = (value: Buffer | string) => createHash('sha256').update(value).digest('hex');
const read = (file: string) => fs.readFileSync(path.join(root, file));
const manifest = JSON.parse(read('public/flow-fonts/manifest.json').toString()) as {
  version: string; shards: Array<{ file: string; bytes: number; sha256: string }>;
};
const corpus = JSON.parse(read('data/corpus-manifest.json').toString()) as {
  version: string; files: Array<{ path: string }>;
};
if (!/^[a-zA-Z0-9_-]{10,64}$/.test(manifest.version)) throw new Error('Invalid font release version');
let corpusDigest = createHash('sha256').update(read('data/corpus-manifest.json'));
for (const entry of corpus.files) {
  const target = path.resolve(root, entry.path);
  if (!target.startsWith(path.join(root, 'data') + path.sep) || !fs.statSync(target).isFile()) throw new Error('Invalid corpus release path');
  corpusDigest = corpusDigest.update(fs.readFileSync(target));
}
const destination = path.join(root, 'public/flow-assets/v-' + manifest.version);
fs.mkdirSync(destination, { recursive: true });
for (const shard of manifest.shards) {
  if (!/^[a-z0-9_-]+\.woff$/.test(shard.file)) throw new Error('Invalid font shard name');
  const bytes = read('public/flow-fonts/' + shard.file);
  if (bytes.byteLength !== shard.bytes || hash(bytes) !== shard.sha256) throw new Error('Font shard integrity failed: ' + shard.file);
  fs.writeFileSync(path.join(destination, shard.file), bytes);
}
fs.copyFileSync(path.join(root, 'public/flow-fonts/manifest.json'), path.join(destination, 'manifest.json'));
const curated = createRequire(import.meta.url)('../shared/flow/curated-data') as { version: string };
const corpusHash = corpusDigest.digest('hex');
const fontHash = hash(read('public/flow-fonts/manifest.json'));
const sourceDigest = createHash('sha256');
function addSource(relative: string) {
  const absolute = path.join(root, relative);
  for (const entry of fs.readdirSync(absolute, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const file = path.join(relative, entry.name);
    if (entry.isDirectory()) addSource(file);
    else if (entry.isFile() && file !== 'src/lib/flow-browser/release.generated.ts' && /\.(?:js|ts|tsx|css)$/.test(entry.name)) {
      sourceDigest.update(file).update(fs.readFileSync(path.join(root, file)));
    }
  }
}
for (const directory of ['src', 'shared', 'miniprogram/flow', 'miniprogram/content', 'scripts']) addSource(directory);
for (const file of ['package.json', 'next.config.js', 'Dockerfile', 'docker-compose.yml', 'nginx.conf']) {
  sourceDigest.update(file).update(read(file));
}
const codeHash = sourceDigest.digest('hex');
let commit = process.env.INFIDAO_RELEASE_COMMIT || '';
if (!commit) try { commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim(); } catch { commit = 'unavailable'; }
let worktreeDirty: boolean | null = null;
try { worktreeDirty = !!execFileSync('git', ['status', '--porcelain', '--untracked-files=no'], { cwd: root, encoding: 'utf8' }).trim(); } catch { /* Git metadata is not present in a container build. */ }
const release = {
  id: process.env.INFIDAO_RELEASE_ID || hash(codeHash + corpusHash + fontHash + curated.version).slice(0, 16),
  commit, worktreeDirty, codeSha256: codeHash, corpusVersion: corpus.version, corpusSha256: corpusHash,
  curatedVersion: curated.version, fontVersion: manifest.version, fontManifestSha256: fontHash,
  fontBasePath: '/flow-assets/v-' + manifest.version, storageSchema: { browser: 2, server: 1 },
};
const releaseDirectory = path.join(root, 'public/flow-releases');
fs.mkdirSync(releaseDirectory, { recursive: true });
fs.writeFileSync(path.join(releaseDirectory, release.id + '.json'), JSON.stringify(release, null, 2) + '\n');
fs.rmSync(path.join(destination, 'release.json'), { force: true }); // Remove an older generator's mutable manifest.
fs.writeFileSync(path.join(root, 'src/lib/flow-browser/release.generated.ts'),
  '// Generated by scripts/build-web-flow-assets.ts.\nexport const FLOW_RELEASE = ' + JSON.stringify(release) + ' as const;\n');
console.log(JSON.stringify({ release: release.id, fontVersion: release.fontVersion, corpusVersion: release.corpusVersion,
  fontShards: manifest.shards.length, storageSchema: release.storageSchema }));
