// Build public resources only. Never load environment files or credentials.
import fs from 'node:fs';
import path from 'node:path';
import { build } from 'esbuild';
import { flowCorpus } from '../src/lib/flow/candidates';
import { lexicalBreaks } from '../src/lib/flow/lexemes';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';

const root = path.resolve('miniprogram');
const generated = path.join(root, 'flow/generated');
const packagePrefix = 'packages/local-';
const MAX_BYTES = 1400 * 1024;
const write = (relative: string, text: string) => {
  const file = path.join(root, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text);
};

async function main() {
  fs.mkdirSync(generated, { recursive: true });
  const adapters: Record<string, string> = {
    'node:crypto': 'export const randomUUID = () => host.randomUUID();',
    '@/lib/data/corpus': 'export const loadCorpus = () => host.loadCorpus();',
    './model': 'export const flowModelConfig = () => host.config(); export const flowJson = (system, input, signal) => host.flowJson(system, input, signal);',
  };
  const result = await build({ stdin: { contents: 'export {runFlow, resetFlowState} from "./src/lib/flow/service";', resolveDir: process.cwd(), loader: 'ts' },
    bundle: true, write: false, minify: true, platform: 'browser', format: 'iife', globalName: 'LocalCore', target: 'es2018',
    plugins: [{ name: 'wechat-native-ports', setup(b) {
      b.onResolve({ filter: /^(node:crypto|@\/lib\/data\/corpus|\.\/model)$/ }, args =>
        adapters[args.path] && (args.path !== './model' || args.importer.includes('/flow/')) ? { path: args.path, namespace: 'wechat-port' } : undefined);
      b.onLoad({ filter: /.*/, namespace: 'wechat-port' }, args => ({ contents: adapters[args.path]!, loader: 'js' }));
    } }] });
  write('flow/generated/local-core.js', '// Generated by scripts/build-wechat-local-core.ts\nmodule.exports = function(host) { const structuredClone = value => JSON.parse(JSON.stringify(value));\n' + result.outputFiles[0]!.text + '\nreturn LocalCore; };\n');
  const corpus = await flowCorpus();
  const curated = createRequire(import.meta.url)('../miniprogram/content/passages.js').passages as Record<string, { fullText: string }>;
  write('content/lexical-breaks.js', '// Generated canonical word boundaries; phones do not depend on Intl.Segmenter.\nmodule.exports = ' +
    JSON.stringify(Object.fromEntries(Object.entries(curated).map(([id, frame]) => [id, {
      ends: lexicalBreaks(frame.fullText), textHash: createHash('sha256').update(frame.fullText).digest('hex'),
    }]))) + ';\n');
  const groups: string[][] = [[]]; let bytes = 0;
  for (const row of corpus) {
    const json = JSON.stringify(row), size = Buffer.byteLength(json) + 2;
    if (size > MAX_BYTES) throw new Error('A corpus record exceeds the package budget');
    if (bytes + size > MAX_BYTES) { groups.push([]); bytes = 0; }
    groups[groups.length - 1]!.push(json); bytes += size;
  }
  const packages: Array<{ root: string; name: string; pages: string[] }> = [];
  const corpusLoaders: string[] = [];
  groups.forEach((rows, index) => {
    const name = 'local-corpus-' + index, pack = 'packages/' + name;
    write(pack + '/records.js', 'module.exports = [\n' + rows.join(',\n') + '\n];\n');
    packages.push({ root: pack, name, pages: [] });
    corpusLoaders.push("() => require.async('../../" + pack + "/records.js')");
  });
  const manifest = JSON.parse(fs.readFileSync('public/flow-fonts/manifest.json', 'utf8'));
  write('assets/fonts/classic.wxss', '/* Generated font fallbacks for canonical text only. */\n.classic-text { font-family: "RunZhiJiaKangXiZidian", "InfiDaoSerifSupplement", ' +
    manifest.shards.map((shard: { id: string }) => '"InfiDao-' + shard.id + '"').join(', ') +
    ', "Songti SC", "STSong", "Noto Serif CJK SC", "SimSun", serif; font-weight: 400; }\n');
  const fontLoaders: string[] = []; let fontPackage = 0, fontBytes = 0;
  for (const shard of manifest.shards as Array<{ id: string; file: string }>) {
    const data = fs.readFileSync(path.join('public/flow-fonts', shard.file)).toString('base64');
    const js = 'module.exports = ' + JSON.stringify(data) + ';\n';
    if (fontBytes + Buffer.byteLength(js) > MAX_BYTES) { fontPackage++; fontBytes = 0; }
    const name = 'local-fonts-' + fontPackage, pack = 'packages/' + name;
    if (!packages.some(entry => entry.root === pack)) packages.push({ root: pack, name, pages: [] });
    write(pack + '/' + shard.id + '.js', js); fontBytes += Buffer.byteLength(js);
    fontLoaders.push(JSON.stringify(shard.id) + ": () => require.async('../../" + pack + '/' + shard.id + ".js')");
  }
  write('flow/generated/resources.js', '// Generated public data imports; paths must stay literal for WeChat package analysis.\n' +
    'const corpus = [' + corpusLoaders.join(',\n') + '];\nconst fonts = {' + fontLoaders.join(',\n') + '};\n' +
    'let pending;\nmodule.exports = { manifest: ' + JSON.stringify(manifest) + ',\n' +
    'loadCorpus() { if (!pending) pending = Promise.all(corpus.map(load => load())).then(parts => parts.flat()).catch(error => { pending = null; throw error; }); return pending; },\n' +
    'loadFont(id) { if (!fonts[id]) return Promise.reject(new Error("FONT_UNCOVERED")); return fonts[id](); } };\n');
  const appFile = path.join(root, 'app.json'), app = JSON.parse(fs.readFileSync(appFile, 'utf8'));
  app.subPackages = [...(app.subPackages || []).filter((entry: { root: string }) => !entry.root.startsWith(packagePrefix)), ...packages];
  fs.writeFileSync(appFile, JSON.stringify(app, null, 2) + '\n');
  const sizes = packages.map(pack => ({ name: pack.name, bytes: fs.readdirSync(path.join(root, pack.root)).reduce((n, name) => n + fs.statSync(path.join(root, pack.root, name)).size, 0) }));
  if (sizes.some(pack => pack.bytes >= 2 * 1024 * 1024)) throw new Error('Generated resource package exceeds 2 MiB');
  console.log(JSON.stringify({ records: corpus.length, coreBytes: result.outputFiles[0]!.text.length, packages: sizes }, null, 2));
}
main().catch(error => { console.error(error.message); process.exitCode = 1; });
